### ISSUE TITLE
Heroku not working

### ISSUE THREAD

**Issue by FlameRender** [FlameRender/fuzzy-octo-umbrella-quebec#1]

**Comment by barrycumbie** [comment]
commenting from your info on the README....

looks like your `readDB()` f/n returns an array item. 

Then, you are trying to invoke an object <kbd>{ }</kbd> property: `something.Random`

What is missing are generous use of `console.log` to see what exactly is being returned. 

What `something` is returned initially
what is `somethign[0]` 
what is the `something` in your <kbd>get to slash</kbd> endpoint 
what is `something.Random` in there too?

**Comment by FlameRender** [comment]
Something is returned as object array [object, object object, object]
something.random returns as undefined but resolves in index.ejs as it should 

Other console logs added to code
