### ISSUE TITLE
localhost error AND heroku refresh error

### ISSUE THREAD

**Issue by barrycumbie** [FlameRender/fuzzy-octo-umbrella-quebec#2]
https://github.com/FlameRender/fuzzy-octo-umbrella-quebec/blob/96594ab9f5ae01b36a9aeba6d73c1abfa0d6d920/utils/UserUtil.js#L13

I cannot confirm but suspect this has something to do with it. 

You should only set the value of a `const` once. You are doing it on each f/n. Move that declaration up above your userUtil class.

**Comment by FlameRender** [comment]
I know there isnt an official pull request to close this but issue resolved and problem remains. New information added to readme, see discovery and fixes to try.
